### PR TITLE
Document HUBOT_IRC_USERNAME

### PR DESCRIPTION
**Pull request by notpeter**
This just adds a couple lines to the readme.md documenting the hubot_irc_username parameter.

### CODE REVIEW

**Comment by parkr** [comment]
Cool. :+1:

**Comment by notpeter** [comment]
It's been 10 months, merge?

**Comment by jgable** [comment]
Are you interested in being a collaborator on the project?

**Comment by notpeter** [comment]
Sure.

**Comment by jgable** [comment]
Oh, guess I don't have that permission on this repo.  @nandub Can you give me project admin privileges so we can get some more active maintainers on the project?  It's clear that we both don't have much time for this project any more (I don't actually use it any longer).

**Comment by notpeter** [comment]
ping @nandub @jgable

**Comment by nandub** [comment]
Sorry I totally missed this.

**Comment by nandub** [comment]
I just added @notpeter as collaborator

**Pull request merged**
