### PR TITLE
Fix Issue For robot.messageRoom

### LINKED ISSUE #173: Adapter doesn't work with robot.messageRoom
When you attempt to call `robot.messageRoom room message` from hubot whilst using this adapter, there is a TypeError as it can't find the `_getTargetFromEnvelope` function in the current scope. Here's the stack trace:

```
TypeError: this._getTargetFromEnvelope is not a function
 at Robot.IrcBot.send (/path/to/hubot/node_modules/hubot-irc/src/irc.coffee:20:14, <js>:48:21)
 at Robot.messageRoom (/path/to/hubot/node_modules/hubot/src/robot.js:608:23)
 at robot.router.post (/path/to/hubot/scripts/simon-says.js:58:7)
 at callbacks (/path/to/hubot/node_modules/express/lib/router/index.js:164:37)
 at param (/path/to/hubot/node_modules/express/lib/router/index.js:138:11)
 at pass (/path/to/hubot/node_modules/express/lib/router/index.js:145:5)
 at Router._dispatch (/path/to/hubot/node_modules/express/lib/router/index.js:173:5)
 at Object.router (/path/to/hubot/node_modules/express/lib/router/index.js:33:10)
 at next (/path/to/hubot/node_modules/connect/lib/proto.js:174:15)
 at Object.multipart [as handle] (/path/to/hubot/node_modules/connect-multiparty/index.js:42:27)
 at next (/path/to/hubot/node_modules/connect/lib/proto.js:174:15)
 at Object.urlencodedParser [as handle] (/path/to/hubot/node_modules/body-parser/lib/types/urlencoded.js:81:44
 at next (/path/to/hubot/node_modules/connect/lib/proto.js:174:15)
 at /path/to/hubot/node_modules/body-parser/lib/read.js:121:5
 at invokeCallback (/path/to/hubot/node_modules/raw-body/index.js:262:16)
 at done (/path/to/hubot/node_modules/raw-body/index.js:251:7)
 at IncomingMessage.onEnd (/path/to/hubot/node_modules/raw-body/index.js:307:7)
 at emitNone (events.js:106:13)
 at IncomingMessage.emit (events.js:208:7)
 at endReadableNT (_stream_readable.js:1055:12)
 at _combinedTickCallback (internal/process/next_tick.js:138:11)
 at process._tickCallback (internal/process/next_tick.js:180:9)<br>
```

I suspect as this function isn't defined in the adapter, the scope may be on the robot object? Using hubot v3.0.1.

### PR DESCRIPTION
**Pull request by phily245**
A TypeError was being thrown due to the wrong scope being used when this command was run

Closes #173

### CODE REVIEW

**Comment by skddc** [comment]
I just ran into the same issue (also on 3.x). For some scripts it would work, but not for others. I can confirm that this change fixes it.

**Comment by laf** [comment]
Being running this in production for over a month now. Would be good if it could be merged into master.

**Comment by notpeter** [comment]
@phily245  Thanks for this.

@nandub If you invite me as a maintainer to npmjs I can do a point release with this. https://www.npmjs.com/package/hubot-irc/access

**Comment by laf** [comment]
Awesome, thanks for merging in.

Let us know when a point release goes out :)

**Comment by phily245** [comment]
Great, thank you! 😊

**Pull request merged**
